language: python
sudo: false
python:
  - "3.8"

install:
  # Setup bikeshed. See https://tabatkins.github.io/bikeshed/#travis-ci
  - pip3 install bikeshed
  - bikeshed update

script:
  - bash ./deploy.sh

env:
  global:
  - ENCRYPTION_LABEL: "189e52c2c347"
  - COMMIT_AUTHOR_EMAIL: "storage-dev@chromium.org"

branches:
  # Don't do this on the gh-pages branch.
  except:
  - gh-pages
